import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import { buildReceipt } from '../src/receipt.mjs';

const schemaUrl = new URL('../docs/receipt.schema.json', import.meta.url);

function realGeneratedReceipt() {
  return buildReceipt({
    codexVersion: '0.147.0',
    platform: 'linux-x64',
    plugin: {
      name: 'sample',
      marketplace: 'local-marketplace',
      sourceRoot: '/workspace'
    },
    declarations: {
      skills: [{ name: 'sample:sample-skill' }],
      hooks: [{ key: 'sample:hook' }],
      mcpServers: ['sample-mcp'],
      apps: [{ id: 'sample-app' }]
    },
    effective: {
      skills: [{ name: 'sample:sample-skill' }],
      hooks: [{ key: 'sample:hook', trustStatus: 'untrusted' }]
    },
    isolation: { mode: 'strict', network: 'denied', hostState: 'denied' }
  });
}

function validateSchema(schema, value, location = '$') {
  const errors = [];
  const actualType = Array.isArray(value)
    ? 'array'
    : value === null
      ? 'null'
      : typeof value;

  if (schema.type !== undefined && actualType !== schema.type) {
    return [`${location}: expected ${schema.type}, received ${actualType}`];
  }
  if (schema.const !== undefined && value !== schema.const) {
    errors.push(`${location}: expected constant ${JSON.stringify(schema.const)}`);
  }
  if (schema.enum !== undefined && !schema.enum.includes(value)) {
    errors.push(`${location}: value is outside the allowed enum`);
  }
  if (typeof value === 'string') {
    if (schema.minLength !== undefined && value.length < schema.minLength) {
      errors.push(`${location}: string is shorter than ${schema.minLength}`);
    }
    if (schema.pattern !== undefined && !(new RegExp(schema.pattern, 'u')).test(value)) {
      errors.push(`${location}: string does not match ${schema.pattern}`);
    }
  }
  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) {
      errors.push(`${location}: array has fewer than ${schema.minItems} items`);
    }
    if (schema.items !== undefined) {
      value.forEach((item, index) => {
        errors.push(...validateSchema(schema.items, item, `${location}[${index}]`));
      });
    }
  }
  if (actualType === 'object') {
    for (const required of schema.required ?? []) {
      if (!Object.hasOwn(value, required)) errors.push(`${location}: missing ${required}`);
    }
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(value)) {
        if (!Object.hasOwn(schema.properties ?? {}, key)) {
          errors.push(`${location}: unexpected property ${key}`);
        }
      }
    }
    for (const [key, childSchema] of Object.entries(schema.properties ?? {})) {
      if (Object.hasOwn(value, key)) {
        errors.push(...validateSchema(childSchema, value[key], `${location}.${key}`));
      }
    }
  }
  return errors;
}

async function receiptSchema() {
  return JSON.parse(await readFile(schemaUrl, 'utf8'));
}

test('checked-in schema accepts a real receipt generated by the production model', async () => {
  const errors = validateSchema(await receiptSchema(), realGeneratedReceipt());

  assert.deepEqual(errors, []);
});

test('checked-in schema rejects missing, extra, and invalid receipt fields', async () => {
  const schema = await receiptSchema();
  const cases = [];

  const missingStatus = structuredClone(realGeneratedReceipt());
  delete missingStatus.status;
  cases.push(missingStatus);

  const extraPluginField = structuredClone(realGeneratedReceipt());
  extraPluginField.plugin.token = 'must-not-be-accepted';
  cases.push(extraPluginField);

  const invalidCapability = structuredClone(realGeneratedReceipt());
  invalidCapability.capabilities[0].status = 'EXECUTED';
  cases.push(invalidCapability);

  const floatingVersion = structuredClone(realGeneratedReceipt());
  floatingVersion.codexVersion = 'latest';
  cases.push(floatingVersion);

  for (const receipt of cases) {
    assert.notDeepEqual(validateSchema(schema, receipt), [], receipt);
  }
});
